#!/bin/sh
#
# arpd		This shell script takes care of starting and stopping arpd
#
# chkconfig:    2345 11 89
# description:	user-space arp daemon
# processname:	arpd
#
# pidfile:	/var/run/arpd.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
if is_no "${NETWORKING}"; then
	msg_network_down arpd
	exit 1
fi

# See how we were called.
case "$1" in
  start)
        # Start daemons.
	if [ ! -f /var/lock/subsys/arpd ]; then
		msg_starting arpd
		daemon arpd -u daemon
		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/arpd
	else
		msg_already_running arpd
	fi
	;;
  stop)
	# Stop daemons.
	if [ -f /var/lock/subsys/arpd ]; then
		msg_stopping arpd
		killproc arpd
		rm -f /var/lock/subsys/arpd >/dev/null 2>&1
	else
		msg_not_running arpd
		exit 1
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	status arpd
	;;
  *)
	msg_usage "$0 {start|stop|restart|status}"
	exit 1
esac
